import { VeyraHomeStage } from '../types';

export const OFFICIAL_BANK_CARD = {
  bankName: 'Birbank / Kapital Bank',
  cardNumber: '4169738849528363',
  formattedCardNumber: '4169 7388 4952 8363',
  cardHolder: 'VEYRA INVEST MMC',
  expireDate: '12/29',
  iban: 'AZ67NABZ01350100000000416973',
  currency: 'AZN',
  supportNote: 'Ödənişi yalnız göstərilən təsdiqlənmiş hesaba göndərin.',
};

export const INITIAL_STAGES: VeyraHomeStage[] = [
  {
    id: 1,
    name: 'Veyra Start',
    minAmount: 25,
    stageTitle: 'Təməl Mərhələsi',
    description: 'Başlanğıc investisiya paketi. Real torpaq analizi və möhkəm təməl layihələndirməsi.',
    features: ['Minimalist təməl arxitekturası', 'Real vaxt portfel monitorinqi', '24/7 dəstək xidməti'],
    badge: 'Başlanğıc',
    riskLevel: 'Çox Aşağı',
    dailyProfitRate: 6.0,
    dailyIncome: 1.5,
    monthlyIncome: 45,
    durationDays: 30,
    commission: '0% Komissiya',
    withdrawalCondition: 'İstənilən vaxt sərbəst çıxarış',
    isActive: true,
    visualStage: 'foundation',
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186156a?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 2,
    name: 'Veyra Build',
    minAmount: 50,
    stageTitle: 'İlk Divarlar və Struktur',
    description: 'Dayanıqlı karkas və monolit divarların ucaldılması, sürətli kapital artımı.',
    features: ['Dayanıqlı karkas struktur', 'Gündəlik mütənasib gəlir hesabatı', 'Şəffaf əməliyyat jurnalı'],
    badge: 'İnkişaf Edir',
    riskLevel: 'Çox Aşağı',
    dailyProfitRate: 6.0,
    dailyIncome: 3.0,
    monthlyIncome: 90,
    durationDays: 30,
    commission: '0% Komissiya',
    withdrawalCondition: 'İstənilən vaxt sərbəst çıxarış',
    isActive: true,
    visualStage: 'walls',
    imageUrl: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 3,
    name: 'Veyra Growth',
    minAmount: 100,
    stageTitle: 'Əsas Konstruksiya',
    description: 'Konstruksiyanın formalaşması, pəncərə və mühəndis komunikasiyalarının quraşdırılması.',
    features: ['Enerji səmərəli mühəndislik', 'Prioritetləşdirilmiş depozit yoxlanışı', 'Genişləndirilmiş analitika'],
    badge: 'Böyümə',
    riskLevel: 'Aşağı',
    dailyProfitRate: 6.0,
    dailyIncome: 6.0,
    monthlyIncome: 180,
    durationDays: 30,
    commission: '0% Komissiya',
    withdrawalCondition: 'İstənilən vaxt sərbəst çıxarış',
    isActive: true,
    visualStage: 'construction',
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 4,
    name: 'Veyra Residence',
    minAmount: 250,
    stageTitle: 'Tam Rezidensiya Konstruksiyası',
    description: 'Müasir fərdi rezidensiya layihəsi, geniş bağ sahəsi və panoramik vitrajlar.',
    features: ['Özəl bağ sahəsi və panoramik pəncərələr', 'Gündəlik sabit aktiv dəyərləndirməsi', 'Şəxsi portfel meneceri'],
    badge: 'Rezidensiya',
    riskLevel: 'Aşağı',
    dailyProfitRate: 6.0,
    dailyIncome: 15.0,
    monthlyIncome: 450,
    durationDays: 30,
    commission: '0% Komissiya',
    withdrawalCondition: 'İstənilən vaxt sərbəst çıxarış',
    isActive: true,
    visualStage: 'residence',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 5,
    name: 'Veyra Premium',
    minAmount: 500,
    stageTitle: 'Premium Fasad və Landşaft',
    description: 'Yüksək keyfiyyətli premium fasad, gecə memarlıq işıqlandırması və qapalı qaraj.',
    features: ['Memarlıq işıqlandırması və qaraj', 'Yüksək gəlir optimizasiyası', 'VIP maliyyə bildirişləri'],
    badge: 'Premium',
    riskLevel: 'Aşağı',
    dailyProfitRate: 6.0,
    dailyIncome: 30.0,
    monthlyIncome: 900,
    durationDays: 30,
    commission: '0% Komissiya',
    withdrawalCondition: 'İstənilən vaxt sərbəst çıxarış',
    isActive: true,
    visualStage: 'premium_facade',
    imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 6,
    name: 'Veyra Prestij',
    minAmount: 750,
    stageTitle: 'Müasir Ev və Hovuz Kompleksi',
    description: 'Geniş sahəli müasir villa, xüsusi açıq istirahət hovuzu və elit landşaft.',
    features: ['İstirahət hovuzu və teras', 'Gəlirlərin sürətli kapitallaşması', 'Prestige Investor statusu'],
    badge: 'Prestij',
    riskLevel: 'Orta',
    dailyProfitRate: 6.0,
    dailyIncome: 45.0,
    monthlyIncome: 1350,
    durationDays: 30,
    commission: '0% Komissiya',
    withdrawalCondition: 'İstənilən vaxt sərbəst çıxarış',
    isActive: true,
    visualStage: 'prestige_pool',
    imageUrl: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 7,
    name: 'Veyra Luxury',
    minAmount: 1000,
    stageTitle: 'Luxury Villa və Landşaft',
    description: 'Ultra-müasir dəbdəbəli villa arxitekturası, avtomatlaşdırılmış hovuz və lüks interyer.',
    features: ['Luxury villa arxitekturası', 'Maksimum diversifikasiyalı aktivlər', 'Luxury Investor sertifikatı'],
    badge: 'Luxury',
    riskLevel: 'Düşünülmüş',
    dailyProfitRate: 6.0,
    dailyIncome: 60.0,
    monthlyIncome: 1800,
    durationDays: 30,
    commission: '0% Komissiya',
    withdrawalCondition: 'İstənilən vaxt sərbəst çıxarış',
    isActive: true,
    visualStage: 'luxury_villa',
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 8,
    name: 'Veyra Elite',
    minAmount: 1200,
    stageTitle: 'Elite Villa Rezidensiyası',
    description: 'Platformadakı ən möhtəşəm aktiv. Geniş hovuz, xüsusi qızılı Elite nişan və fərdi VIP xidmət.',
    features: ['Ən yüksək gəlirlilik əmsalı', 'Fərdi konsyerj və prioritet xidmət', 'Xüsusi Veyra Elite qızılı nişanı'],
    badge: 'Elite Villa',
    riskLevel: 'Düşünülmüş',
    dailyProfitRate: 6.0,
    dailyIncome: 72.0,
    monthlyIncome: 2160,
    durationDays: 30,
    commission: '0% Komissiya',
    withdrawalCondition: 'İstənilən vaxt sərbəst çıxarış',
    isActive: true,
    visualStage: 'elite_villa',
    imageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80',
  },
];
