import { VeyraHomeStage } from '../types';

export const OFFICIAL_BANK_CARD = {
  bankName: 'Birbank / Kapital Bank',
  cardNumber: '4169738849528363',
  formattedCardNumber: '4169 7388 4952 8363',
  cardHolder: 'VEYRA INVEST MMC',
  expireDate: '12/29',
  iban: 'AZ67NABZ01350100000000416973',
  currency: 'AZN',
  supportNote: 'Ödənişi yalnız göstərilən təsdiqlənmiş hesaba göndərin.',
};

export const INITIAL_STAGES: VeyraHomeStage[] = [
  {
    id: 1,
    name: 'Veyra Start',
    minAmount: 25,
    stageTitle: 'Təməl Mərhələsi',
    description: 'Başlanğıc səviyyə. Layihənin təməli qoyulur və investisiya portfeliniz formalaşır.',
    features: ['Minimalist təməl arxitekturası', 'Real vaxt portfel monitorinqi', '24/7 dəstək xidməti'],
    badge: 'Başlanğıc',
    riskLevel: 'Çox Aşağı',
    dailyProfitRate: 0.40,
    durationDays: 30,
    commission: '0% Komissiya',
    withdrawalCondition: 'İstənilən vaxt sərbəst çıxarış',
    isActive: true,
    visualStage: 'foundation',
  },
  {
    id: 2,
    name: 'Veyra Build',
    minAmount: 50,
    stageTitle: 'İlk Divarlar və Struktur',
    description: 'Evdə ilk dayanıqlı divarlar yüksəlir, layihə sürətlə inkişaf edir.',
    features: ['Dayanıqlı karkas struktur', 'Gündəlik mütənasib gəlir hesabatı', 'Şəffaf əməliyyat jurnalı'],
    badge: 'İnkişaf Edir',
    riskLevel: 'Çox Aşağı',
    dailyProfitRate: 0.48,
    durationDays: 45,
    commission: '0% Komissiya',
    withdrawalCondition: 'İstənilən vaxt sərbəst çıxarış',
    isActive: true,
    visualStage: 'walls',
  },
  {
    id: 3,
    name: 'Veyra Growth',
    minAmount: 100,
    stageTitle: 'Əsas Konstruksiya',
    description: 'Evin əsas konstruksiyası formalaşır, fasad pəncərə və qapı elementləri ilə tamamlanır.',
    features: ['Enerji səmərəli mühəndislik', 'Prioritetləşdirilmiş depozit yoxlanışı', 'Genişləndirilmiş analitika'],
    badge: 'Böyümə',
    riskLevel: 'Aşağı',
    dailyProfitRate: 0.55,
    durationDays: 60,
    commission: '0% Komissiya',
    withdrawalCondition: 'İstənilən vaxt sərbəst çıxarış',
    isActive: true,
    visualStage: 'construction',
  },
  {
    id: 4,
    name: 'Veyra Residence',
    minAmount: 250,
    stageTitle: 'Tam Rezidensiya Konstruksiyası',
    description: 'Tam ev konstruksiyası, müasir xarici fasad və şəxsi bağ sahəsi formalaşır.',
    features: ['Özəl bağ sahəsi və panoramik pəncərələr', 'Gündəlik sabit aktiv dəyərləndirməsi', 'Şəxsi portfel meneceri'],
    badge: 'Rezidensiya',
    riskLevel: 'Aşağı',
    dailyProfitRate: 0.62,
    durationDays: 90,
    commission: '0% Komissiya',
    withdrawalCondition: 'İstənilən vaxt sərbəst çıxarış',
    isActive: true,
    visualStage: 'residence',
  },
  {
    id: 5,
    name: 'Veyra Premium',
    minAmount: 500,
    stageTitle: 'Premium Fasad və Landşaft',
    description: 'Yüksək keyfiyyətli premium fasad, memarlıq işıqlandırması, qapalı qaraj və landşaft.',
    features: ['Memarlıq işıqlandırması və qaraj', 'Yüksək gəlir optimizasiyası', 'VIP maliyyə bildirişləri'],
    badge: 'Premium',
    riskLevel: 'Aşağı',
    dailyProfitRate: 0.70,
    durationDays: 120,
    commission: '0% Komissiya',
    withdrawalCondition: 'İstənilən vaxt sərbəst çıxarış',
    isActive: true,
    visualStage: 'premium_facade',
  },
  {
    id: 6,
    name: 'Veyra Prestige',
    minAmount: 750,
    stageTitle: 'Müasir Ev və Hovuz Kompleksi',
    description: 'Böyük və müasir villa, xüsusi hovuz kompleksi, geniş bağ və zərif interyer.',
    features: ['İstirahət hovuzu və teras', 'Gəlirlərin sürətli kapitallaşması', 'Prestige Investor statusu'],
    badge: 'Prestige',
    riskLevel: 'Orta',
    dailyProfitRate: 0.78,
    durationDays: 180,
    commission: '0% Komissiya',
    withdrawalCondition: 'İstənilən vaxt sərbəst çıxarış',
    isActive: true,
    visualStage: 'prestige_pool',
  },
  {
    id: 7,
    name: 'Veyra Luxury',
    minAmount: 1000,
    stageTitle: 'Luxury Villa və Landşaft',
    description: 'Geniş sahəli luxury villa, avtomatlaşdırılmış hovuz, çoxmaşınlı qaraj və lüks interyer.',
    features: ['Luxury villa arxitekturası', 'Maksimum diversifikasiyalı aktivlər', 'Luxury Investor sertifikatı'],
    badge: 'Luxury Investor',
    riskLevel: 'Düşünülmüş',
    dailyProfitRate: 0.86,
    durationDays: 240,
    commission: '0% Komissiya',
    withdrawalCondition: 'İstənilən vaxt sərbəst çıxarış',
    isActive: true,
    visualStage: 'luxury_villa',
  },
  {
    id: 8,
    name: 'Veyra Elite',
    minAmount: 1200,
    stageTitle: 'Elite Villa Rezidensiyası',
    description: 'Platformadakı ən yüksək səviyyə. Möhtəşəm həyət, geniş hovuz, premium gecə işıqlandırması və xüsusi Elite badge.',
    features: ['Ən yüksək gəlirlilik əmsalı', 'Fərdi konsyerj və prioritet xidmət', 'Xüsusi Veyra Elite qızılı nişanı'],
    badge: 'Elite Villa',
    riskLevel: 'Düşünülmüş',
    dailyProfitRate: 0.95,
    durationDays: 365,
    commission: '0% Komissiya',
    withdrawalCondition: 'İstənilən vaxt sərbəst çıxarış',
    isActive: true,
    visualStage: 'elite_villa',
  },
];
